# Generated by Django 4.2.2 on 2023-06-13 16:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_alter_post_elevation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-date"]},
        ),
    ]
