# Generated by Django 4.2.2 on 2023-06-13 16:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0004_rename_length_post_hike_length"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={},
        ),
    ]
