# Generated by Django 4.2.2 on 2023-06-13 17:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0005_alter_post_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-date"]},
        ),
    ]
