# Generated by Django 4.2.2 on 2023-06-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0006_alter_post_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
